# Generated by Django 3.0.5 on 2020-05-01 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_auto_20200501_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_applicant',
            new_name='is_student',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_recruiter',
            new_name='is_teacher',
        ),
    ]
