# Generated by Django 3.0.5 on 2020-05-08 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_auto_20200501_2018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='interests',
            new_name='applications',
        ),
    ]
